### ISSUE TITLE
Game Window Pane

### ISSUE THREAD

**Issue by embronk** [bjucps209/spring22-team1#8]
The Game window pane is off a little bit and in a couple of levels the enemy troops, weather, and/or cities go off of the pane.

**Comment by embronk** [comment]
Game window is fine when in full screen mode, but above happens when escape is clicked

**Comment by RFuller25** [comment]
Seems fine to me, I'm not getting any of the bugs when I escape from full screen
¯\_(ツ)_/¯
Let me know if you keep getting it @embronk

**Comment by RFuller25** [comment]
![image](https://user-images.githubusercontent.com/89529399/165195151-cb914b60-a8b9-4aad-8e38-f839ee9cd49c.png)
- image from @embronk
